#!/usr/bin/env sh

# for autostart launch yabai
sudo /Users/chenzhi/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bar settings
# 打开状态栏
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off

yabai -m config window_border                on
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0xff32a831
yabai -m config normal_window_border_color   0x00010101
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


# status_bar
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.6

# general space settings(设置间隔,都设置成0)
#yabai -m config layout                       bsp
yabai -m config --space 1 layout             bsp
yabai -m config --space 2 layout             bsp
yabai -m config --space 3 layout             float 
yabai -m config --space 4 layout             bsp
yabai -m config --space 5 layout             bsp
yabai -m config --space 6 layout             bsp
# 3 space used for float 

yabai -m config top_padding                  24
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   4 # no need when opacity is on

#yabai -m rule --add app=".*" manage=off

# apps should be bsp
yabai -m rule --add app="^Microsoft.*Edge$" manage=on
yabai -m rule --add app="^Alacritty$" manage=on
yabai -m rule --add app="^kitty$" manage=on

# move to space 3
yabai -m rule --add app="^QQ.*$" space=^3 manage=off
yabai -m rule --add app="^网易云.*$" space=^3  manage=off

yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Clash.*$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^App.*$" manage=off
yabai -m rule --add app="^Preference.*$" manage=off
yabai -m rule --add app="^系统偏好设置.*$" manage=off
yabai -m rule --add app="^Karabiner.*$" manage=off
yabai -m rule --add app="^System.*$" manage=off
yabai -m rule --add app="^Spotify.*$" manage=off
yabai -m rule --add app="^系统.*$" manage=off
yabai -m rule --add app="^微信.*$" manage=off
yabai -m rule --add app="^自动操作.*$" manage=off
yabai -m rule --add app="^脚本.*$" manage=off
yabai -m rule --add app="^腾讯.*$" manage=off
yabai -m rule --add app="^百度.*$" manage=off
yabai -m rule --add app="^Transmission.*$" manage=off
yabai -m rule --add app="^迅雷.*$" manage=off
yabai -m rule --add app="^活动.*$" manage=off
yabai -m rule --add app="^Krita.*$" manage=off
yabai -m rule --add app="^关于.*$" manage=off
yabai -m rule --add app="^Raycast.*$" manage=off
yabai -m rule --add app="^Joplin.*$"  manage=off


